CREATE TABLE notes (
    id       TEXT    PRIMARY KEY,
    title     TEXT,
    author TEXT,
    text    TEXT,
    date    TEXT,
    color   TEXT
);

CREATE TABLE dev_academy (
    id    TEXT PRIMARY KEY,
    nome  TEXT,
    senha TEXT
);

CREATE TABLE settings (
    key    TEXT PRIMARY KEY,
    value  TEXT
);


INSERT INTO notes (id, title, author, text, date, color) values ("1", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("2", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#CBAACB");
INSERT INTO notes (id, title, author, text, date, color) values ("3", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFFFB5");
INSERT INTO notes (id, title, author, text, date, color) values ("4", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFCCB6");
INSERT INTO notes (id, title, author, text, date, color) values ("5", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#F3B0C3");
INSERT INTO notes (id, title, author, text, date, color) values ("6", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#C6DBDA");
INSERT INTO notes (id, title, author, text, date, color) values ("7", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("8", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("9", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("1", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("10", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("11", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#CBAACB");
INSERT INTO notes (id, title, author, text, date, color) values ("12", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFFFB5");
INSERT INTO notes (id, title, author, text, date, color) values ("13", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFCCB6");
INSERT INTO notes (id, title, author, text, date, color) values ("14", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#F3B0C3");
INSERT INTO notes (id, title, author, text, date, color) values ("15", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#C6DBDA");
INSERT INTO notes (id, title, author, text, date, color) values ("16", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("17", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#CBAACB");
INSERT INTO notes (id, title, author, text, date, color) values ("18", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFFFB5");
INSERT INTO notes (id, title, author, text, date, color) values ("19", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFCCB6");
INSERT INTO notes (id, title, author, text, date, color) values ("20", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#F3B0C3");
INSERT INTO notes (id, title, author, text, date, color) values ("21", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#C6DBDA");
INSERT INTO notes (id, title, author, text, date, color) values ("22", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#ABDEE6");
INSERT INTO notes (id, title, author, text, date, color) values ("23", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#CBAACB");
INSERT INTO notes (id, title, author, text, date, color) values ("24", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFFFB5");
INSERT INTO notes (id, title, author, text, date, color) values ("25", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#FFCCB6");
INSERT INTO notes (id, title, author, text, date, color) values ("26", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#F3B0C3");
INSERT INTO notes (id, title, author, text, date, color) values ("27", "Mussum Ipsum, cacilds vidis litro abertis.", "Renan Breno", "Mussum Ipsum, cacilds vidis litro abertis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Pra lá , depois divoltis porris, paradis. Sapien in monti palavris qui num significa nadis i pareci latim. Delegadis gente finis, bibendum egestas augue arcu ut est.", "12/03/2021", "#C6DBDA");
